PROGRAM Hello(INPUT, OUTPUT);
BEGIN
  WRITELN('Hello world!');
END;
PROGRAM Hello(INPUT, OUTPUT);
BEGIN
  WRITELN('Hello world!');
END;
PROGRAM Hello(INPUT, OUTPUT);
BEGIN
  WRITELN('Hello world!');
END;
PROGRAM Hello(INPUT, OUTPUT);
BEGIN
  WRITELN('Hello world!');
END;
PROGRAM Hello(INPUT, OUTPUT);
BEGIN
  WRITELN('Hello world!');
END